// SPDX-FileCopyrightText: 2026 Beamstack <https://beam-stack.com>
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * ⚠⚠ THE MODEL ENUMERATION QUERY — the one query that answers *"what elements are actually in this
 * model?"*, and the project-wide quantity roll-up built on it (`P5_step6A_enumeration_design.md`).
 *
 * **Why it exists.** The 2026-07-25 adversarial sweep (Entry 57, finding 2) measured that **the model
 * cannot be enumerated**: `scene.elements` is the AUTHORED ROWS, which is not the set of real elements.
 * Three separate consumers — the project quantity roll-up, the schedules (D58), and the Clean Delta
 * exporter — each need the same walk, and each had been writing it by hand. The plan's own instruction:
 *
 *   > *"BUILD THE PROJECT-WIDE QUANTITIES PATH, AND **MAKE IT A COMMAND/QUERY, NOT A LOOP EVERY
 *   > CONSUMER REWRITES**"* — `v1.0.0_imp_plan.md`, P5 exit criteria.
 *
 * ⚠ **This is additive and touches nothing frozen** (D19, `core_logic.md` rule 5). No stored byte, no
 * `SCENE_SCHEMA_VERSION` bump, no new field on `PartQuantity` — the LBS address rides on the *row*.
 *
 * ⚠⚠ **THE MEASUREMENT THAT SHAPED IT** (design §1, real OCCT, real `@bunyan/types`): a building of
 * **3 authored rows** holds **19 real elements**; 15 carry their own parts and **4 carry none**. The
 * naive `for (id of Object.keys(scene.elements)) await doc.quantities(id)` counted **2** and threw.
 *
 * ⚠⚠ AND THE FINDING THAT WIDENED THE RULE — *"skip voids"* IS THE WRONG RULE. Both `review_P4.md`
 * (2026-07-14) and Entry 57 named **the Opening** as what kills the loop (*"a void has no parts"*).
 * Measured, the loop dies on the **CURTAIN WALL** — a **pure composite** parent, which has no own parts
 * BY DESIGN (`curtainwall.ts`: *"NO buildGeometry — a pure composite"*). A rule written to skip voids
 * specifically would have shipped green and still crashed on the very element D59 was built to prove.
 * The honest rule is **"an element with no OWN parts contributes no quantity rows"**, and it has two
 * populations. *(The ⓙ door is in neither — it has a leaf and a frame, and it is measured.)*
 */

import type {
  Classification,
  ContainerId,
  Element,
  ElementId,
  MaterialId,
  Params,
  StyleId,
  TypeId,
} from './entities.js';
import type { ElementGeometry } from './build.js';
import type { Scene } from './scene.js';
import { containerPath } from './scene.js';
import { isElementActive, optionScopeOf } from './designoptions.js';
import type { ActiveOptions, DesignOption, DesignOptionId } from './designoptions.js';
import type { PartQuantity } from './document.js';

/** The separator between container names in an LBS address — `Site/Tower A/Level 1`. */
const LBS_SEP = '/';

/**
 * ONE REAL ELEMENT of the model: an authored `scene.elements` row, or a generated descendant of one
 * (D59 Model A — a curtain wall's columns, panels and mullions).
 *
 * ⚠ A derived child is a first-class element with its own PEI (`${parentId}:${slot}`), its own Type and
 * its own parts — a tag, a schedule row and a Clean Delta row all bind to it. It is simply not *stored*,
 * because it is derived from the parent's recipe (recipe-is-truth, D30).
 */
export interface ModelElement {
  /** The PEI — an authored prefixed ULID (D44), or a derived `${parentId}:${slot}` (D59). */
  readonly id: ElementId;
  readonly typeId: TypeId;
  /** The authored `scene.elements` row this belongs to — itself, when this element IS one. */
  readonly rootId: ElementId;
  /** `true` ⇒ a GENERATED child (D59). Never a scene row; regenerated by every rebuild. */
  readonly derived: boolean;
  /** Inherited from `rootId` for a derived child — a panel sits on the storey its curtain wall does. */
  readonly containerId?: ContainerId;
  /**
   * ⚠ THE LBS ADDRESS, root-first (`v1.0.0_spec.md` §7a — Planitor's Location Breakdown Structure).
   * Entry 57's gap: `DocumentContext` had no container-path method and `QuantityBreakdown` carried no
   * container address, so the per-container roll-up the plan demands had nowhere to land.
   */
  readonly containerPath: readonly ContainerId[];
  /** The same address as a string — Planitor's `spatial_container_code`. `''` when unplaced. */
  readonly containerCode: string;
  readonly styleId?: StyleId;
  readonly hostId?: ElementId;
  /** The human-facing name a schedule row or a tag renders (⚠ never the PEI — D44: ids are opaque). */
  readonly name?: string;
  /**
   * ⚠ THE INSTANCE PARAMS — carried so a `param` schedule column can be answered from THIS walk
   * (`P5_step6B_schedules_design.md` §4.4). For an authored row these are `scene.elements[id].params`;
   * for a **generated child** (D59) they are the child's own params, which live only on the synthetic
   * `Element` the build carries — a consumer reaching into `scene.elements` could never have found them.
   *
   * ⚠⚠ It is here, and not re-derived at the consumer, for the D74 reason: when a consumer needs a
   * field, add it where the ONE walk already produces it. The alternative was a second walk of the
   * geometry tree inside the schedule body — precisely the duplication this module exists to prevent.
   */
  readonly params: Params;
  /**
   * ⚠ The AUTHORED short label a schedule's identity column reads (`Element.mark`, reserved ⓡ).
   * ⚠⚠ Absent for a generated child, and that is structural rather than an oversight: a mark is
   * authored, and a D59 child is not a scene row. `ChildOverride.mark?` is reserved (owner Q3,
   * 2026-07-28) as the eventual home; nothing reads `childOverrides` in v1.0.0, so a child's mark is
   * absent today and a child's identity column is its Type-supplied `name`.
   */
  readonly mark?: string;
  readonly classification?: Classification;
  /**
   * The build outcome, carried through so a consumer never has to ask a second question.
   *
   * ⚠⚠ AN ELEMENT NOBODY HAS BUILT IS `stale`, NEVER `failed` (D66 §3c, T-005). `stale` means *recipe
   * present, solid not built*; `failed`+`unbuildable` means a Type refused. A consumer acts on the
   * first by building it and on the second by fixing the model, and under lazy build the two
   * populations differ by nearly the whole building.
   *
   * ⚠ `'stale'` is the one member `ElementGeometry['state']` does not carry, and structurally so: it is
   * the state of an element that has NO `ElementGeometry` at all.
   */
  readonly state: ElementGeometry['state'] | 'stale';
  /**
   * Why it failed, when it did (D42 `geometry` vs D43 `unbuildable` — the load-bearing distinction).
   *
   * ⚠ Absent on a `stale` element: nothing failed, so there is no reason to give.
   */
  readonly failure?: ElementGeometry['failure'];
  /**
   * `false` ⇒ a pure void or a pure composite: real, enumerated, but contributing no quantity (§2.3).
   *
   * ⚠ **Read it only after `state`.** On a `stale` element it is `false` because nothing is built yet,
   * not because the element has nothing to measure — the two are indistinguishable from this field
   * alone. Every consumer here tests `state !== 'valid'` first, which is what keeps them apart.
   */
  readonly hasParts: boolean;
}

/** How a consumer resolves design options while enumerating (D65 + the D67 cascade). */
export interface EnumerateOptions {
  /** The active option per set. Absent/unlisted set ⇒ that set's primary option. */
  readonly active?: ActiveOptions;
  /**
   * The option catalogue. A consumer that already holds one (Planitor/Miqdar) supplies it here instead of
   * letting this fall back to the document's own `scene.designOptions` (`core.createDesignOption`/
   * `updateDesignOption`/`deleteDesignOption`, T-011/D85, are that catalogue's authoring verbs).
   */
  readonly designOptions?: Readonly<Record<DesignOptionId, DesignOption>>;
}

/** One measured part of one real element, carrying the address a consumer groups it by. */
export interface ProjectQuantityRow {
  readonly elementId: ElementId;
  readonly rootId: ElementId;
  readonly typeId: TypeId;
  readonly containerPath: readonly ContainerId[];
  readonly containerCode: string;
  readonly part: PartQuantity;
}

/**
 * A real element that could NOT be measured, and why.
 *
 * ⚠⚠ OWNER-RULED 2026-07-25 (design §4 Q1): it is REPORTED, never zeroed and **never silently dropped.**
 * Domain rule 15 forbids the zero (*an unmeasurable quantity is OMITTED, never zeroed*) — but silently
 * dropping an element from a **project-wide total** is the same silent wrongness one level up: the total
 * would be plausible and short, which is exactly what makes it dangerous.
 */
export interface UnmeasuredElement {
  readonly elementId: ElementId;
  readonly reason: string;
}

export interface ProjectQuantities {
  readonly rows: readonly ProjectQuantityRow[];
  /** Every real element that could not be measured (§2.4). Empty ⇒ the totals are complete. */
  readonly unmeasured: readonly UnmeasuredElement[];
  /** ⚠ `exact`, always, and it stays honest precisely because `unmeasured` exists beside it (rule 15). */
  readonly basis: 'exact';
}

/**
 * ⚠⚠ THE FORCE SET (D66 §3c, T-005) — the authored rows this document has not built.
 *
 * `rebuildOnly(deferredElements(...))` is what an aggregate runs before it enumerates, so it reports on
 * the model rather than on whatever the last partial build happened to touch. It is empty on a fully
 * built document, which is why FORCE costs nothing outside lazy build.
 *
 * ⚠ Authored rows only. A D59 child is not a scene row and cannot be built on its own — it arrives with
 * its parent, which is the same reason `rebuildOnly` builds whole assemblies.
 *
 * @param ids Bound the set to these ids; omit for the whole model. The Clean Delta bounds it to the
 *   delta, because owner ruling Q2 makes that exporter's cost track the size of the CHANGE.
 */
export function deferredElements(
  scene: Scene,
  geometryOf: (id: ElementId) => ElementGeometry | undefined,
  ids?: Iterable<ElementId>,
): readonly ElementId[] {
  const out: ElementId[] = [];
  for (const id of ids ?? Object.keys(scene.elements)) {
    if (scene.elements[id] === undefined) continue;
    if (geometryOf(id) === undefined) out.push(id);
  }
  return out;
}

/** The spatial container chain as a readable address — `Site/Tower A/Level 1`. `''` when unplaced. */
export function containerCode(scene: Scene, id: ContainerId | undefined): string {
  return containerPath(scene, id)
    .map((c) => c.name)
    .join(LBS_SEP);
}

/**
 * ⚠⚠ THE ENUMERATION. Every real element of the model, in one walk.
 *
 * Synchronous and kernel-free by construction: it reads the recipe (`scene`) and the ALREADY-BUILT
 * geometry tree. A schedule that wants the element list without measuring pays nothing.
 *
 * ⚠ It reads the BUILT tree because a generated child only exists once its parent has been built —
 * deriving children *is* the build (D59 Model A), and re-deriving them here would be a second build
 * path duplicating the engine.
 *
 * ⚠⚠ **SO AN UNBUILT PARENT'S D59 CHILDREN ARE NOT ENUMERATED AT ALL, AND THAT IS WHY EVERY AGGREGATE
 * FORCES** (D66 §3c, T-005). An authored row is always reported, `stale` when nobody built it — but a
 * curtain wall's panels are the build's own output, so a deferred curtain wall costs a schedule its
 * panel rows with nothing left to declare them by. A declaration can only name what it can see; the
 * missing population is invisible by construction, so `deferredElements` + `rebuildOnly` is the only
 * honest answer for an aggregate, and DECLARE was never actually on the table for it.
 *
 * The four filters, in one place so three products cannot each get them slightly wrong:
 *  1. walk `ElementGeometry.children` — 16 of the measured 19 real elements are invisible without it;
 *  2. exclude non-active design options, WITH the D67 ancestor cascade;
 *  3. an element with no own parts is still ENUMERATED (it has a PEI a tag may bind to) — it simply
 *     yields no quantity rows, which is where filter 3 actually bites (`projectQuantities`);
 *  4. an element that is unbuilt, failed or unbuildable is enumerated with its state, and reported by
 *     the roll-up.
 */
export function modelElements(
  scene: Scene,
  geometryOf: (id: ElementId) => ElementGeometry | undefined,
  options: EnumerateOptions = {},
): readonly ModelElement[] {
  const scope = optionScopeOf(scene, options.designOptions);
  const active = options.active ?? {};
  const out: ModelElement[] = [];

  for (const element of Object.values(scene.elements)) {
    // ⚠ FILTER 2 — the D65/D67 exclusion invariant, applied ONCE per authored row. A generated child
    // needs no test of its own: it is not a scene row, so it is excluded WITH its parent, by
    // construction (D67's own finding — D59's derived-children ruling paying off a second time).
    if (!isElementActive(element, scope, active)) continue;

    const path = containerPath(scene, element.containerId).map((c) => c.id);
    const code = containerCode(scene, element.containerId);
    // ⚠ ONE code path for an authored row and a generated child — the child's synthetic `Element` is
    // carried on its `ElementGeometry` (D59, added while building this query: it was thrown away before,
    // so a panel's Type was unrecoverable). `identity` is that Element either way.
    const walk = (node: ElementGeometry | undefined, identity: Element): void => {
      // An element with no geometry entry at all has never been built. It is still a real, authored
      // element — report it, so the roll-up can say so rather than quietly pretend the model is
      // complete (filter 4).
      //
      // ⚠⚠ NEVER BUILT IS `stale`, NOT `failed`/`unbuildable` (D66 §3c, T-005). Reporting it as
      // `unbuildable` said *"a Type refused this"* about an element nobody had asked for yet, so
      // under lazy build a normal first paint made every aggregate call most of the building broken.
      // `agent.ts` already answered `stale` for the same element through `geometryOf()`.
      out.push({
        id: identity.id,
        typeId: identity.typeId,
        rootId: element.id,
        derived: identity.id !== element.id,
        ...(element.containerId === undefined ? {} : { containerId: element.containerId }),
        containerPath: path,
        containerCode: code,
        ...(identity.styleId === undefined ? {} : { styleId: identity.styleId }),
        ...(identity.hostId === undefined ? {} : { hostId: identity.hostId }),
        ...(identity.name === undefined ? {} : { name: identity.name }),
        params: identity.params,
        ...(identity.mark === undefined ? {} : { mark: identity.mark }),
        ...(identity.classification === undefined
          ? {}
          : { classification: identity.classification }),
        state: node?.state ?? 'stale',
        ...(node === undefined || node.failure === undefined ? {} : { failure: node.failure }),
        hasParts: (node?.parts.length ?? 0) > 0,
      });
      // ⚠ FILTER 1 — the TREE, not one level (rule 18): a curtain wall's column is itself composite.
      for (const child of node?.children ?? []) {
        // A child without a carried Element cannot happen (the engine sets it on both construction
        // paths); if a future build path forgets, fall back to the parent's type rather than crash —
        // a wrong type is visible in a schedule, a thrown enumeration takes the whole roll-up down.
        walk(child, child.element ?? { ...identity, id: child.elementId });
      }
    };
    walk(geometryOf(element.id), element);
  }

  return out;
}

/** Group rows by a key the caller derives — the one grouping primitive, so there is never a second. */
function groupBy<T>(
  rows: readonly ProjectQuantityRow[],
  key: (row: ProjectQuantityRow) => T,
): Map<T, ProjectQuantityRow[]> {
  const out = new Map<T, ProjectQuantityRow[]>();
  for (const row of rows) {
    const k = key(row);
    const bucket = out.get(k);
    if (bucket === undefined) out.set(k, [row]);
    else bucket.push(row);
  }
  return out;
}

/** Totals a bucket of rows. ⚠ `mass` is present only when EVERY row in it had one (rule 15). */
export interface QuantityTotal {
  /** mm³ */
  readonly volume: number;
  /** mm² */
  readonly area: number;
  /** kg — ⚠ ABSENT when any contributing part had no resolvable density. Never a partial sum. */
  readonly mass?: number;
  /** How many parts contributed. */
  readonly parts: number;
  /** How many distinct real elements contributed. */
  readonly elements: number;
}

function total(rows: readonly ProjectQuantityRow[]): QuantityTotal {
  let volume = 0;
  let area = 0;
  let mass = 0;
  let massKnown = true;
  const elements = new Set<ElementId>();
  for (const row of rows) {
    volume += row.part.volume;
    area += row.part.area;
    elements.add(row.elementId);
    // ⚠ A single unresolvable density makes the whole SUM unknown — reporting the partial sum would be
    // an under-count wearing the `exact` badge, which is domain rule 15's failure mode as an aggregate.
    if (row.part.mass === undefined) massKnown = false;
    else mass += row.part.mass;
  }
  return {
    volume,
    area,
    ...(massKnown ? { mass } : {}),
    parts: rows.length,
    elements: elements.size,
  };
}

/** *"How much C25/30 is in this building?"* — the P5 exit criterion, keyed by material id. */
export function totalsByMaterial(
  rows: readonly ProjectQuantityRow[],
): ReadonlyMap<MaterialId, QuantityTotal> {
  return new Map([...groupBy(rows, (r) => r.part.materialId)].map(([k, v]) => [k, total(v)]));
}

/** *"How much is the structural trade's?"* — D45's routing axis, keyed by discipline. */
export function totalsByDiscipline(
  rows: readonly ProjectQuantityRow[],
): ReadonlyMap<string, QuantityTotal> {
  return new Map([...groupBy(rows, (r) => r.part.discipline)].map(([k, v]) => [k, total(v)]));
}

/** *"How much is in Tower A?"* — the LBS roll-up (spec §7a), keyed by `containerCode`. */
export function totalsByContainer(
  rows: readonly ProjectQuantityRow[],
): ReadonlyMap<string, QuantityTotal> {
  return new Map([...groupBy(rows, (r) => r.containerCode)].map(([k, v]) => [k, total(v)]));
}

/** *"How many doors, and how much do they come to?"* — the schedule axis, keyed by `typeId`. */
export function totalsByType(
  rows: readonly ProjectQuantityRow[],
): ReadonlyMap<TypeId, QuantityTotal> {
  return new Map([...groupBy(rows, (r) => r.typeId)].map(([k, v]) => [k, total(v)]));
}
