// Run the naming probe and print what OCCT's history ACTUALLY reports.
//
// The question this answers (spec §4.5): "OCCT history is robust for faces but weakest for edges and
// vertices from boolean section curves" is something we read, not something we measured. This prints
// the measurement.
//
// THE TWO DERIVATIONS IT COMPARES, because either alone would be trusted rather than checked:
//
//   1. HISTORY      — identity / Modified / Generated, as the maker reports them.
//   2. ADJACENCY    — a face's neighbours. If every FACE has a name, then an edge can be named by the
//                     pair of faces it lies between, and a vertex by the set of faces meeting at it.
//                     No history required, no geometry touched.
//
// The interesting number is not how many sub-shapes history covers. It is how many are left
// UNNAMEABLE once BOTH derivations have been applied — because that, and only that, is what the
// naming resolver would have to refuse.
//
//   node tools/kernel-build/probe-history.mjs [--json]

import initBunyanProbe from './dist/bunyan-probe.js';

const wasm = await initBunyanProbe();
const report = JSON.parse(wasm.probe());

if (process.argv.includes('--json')) {
  console.log(JSON.stringify(report, null, 2));
  process.exit(0);
}

const pad = (s, n) => String(s).padEnd(n);
const KINDS = ['face', 'edge', 'vertex'];
const rel = (o, name) => o.from.filter((f) => f.endsWith(`(${name})`));

for (const c of report) {
  console.log('\n' + '='.repeat(102));
  console.log(`CASE  ${c.case}`);
  if (c.error) {
    console.log(`  ⚠ ERROR: ${c.error}`);
    continue;
  }
  if (c.note) console.log(`      ${c.note}`);
  if (c.targets) {
    console.log(
      `      the cut produced ${c.cutEdgeCount} edges; ${c.generatedEdgeCount} of them were GENERATED by faces (section curves):`,
    );
    for (const t of c.targets) {
      console.log(`        ${pad(t.curve, 10)} len=${pad(t.length, 12)} mid=[${t.midpoint}]`);
    }
    continue;
  }
  console.log('='.repeat(102));

  const operands = c.operands.map((o) => `${o.name}(${o.faces}F/${o.edges}E/${o.vertices}V)`);
  console.log(
    `  operands: ${operands.join(' + ') || '(none — primitive)'}` +
      `   ⇒  result: ${c.result.faces}F / ${c.result.edges}E / ${c.result.vertices}V`,
  );

  // ---- 0. REVOLVE — the three questions this op exists to settle -------------------------------
  // Printed FIRST, and above the generic history table, because for the revolve these three lines ARE
  // the finding: whether the caps exist, whether each authored segment made exactly one face, and
  // whether a segment on the axis made none.
  if (c.caps) {
    const cap = (side) => {
      const s = c.caps[side];
      if (s.threw) return 'THREW';
      if (s.null) return 'NULL — no cap';
      return s.inResult ? `${s.kind}#${s.face}` : `${s.kind} NOT IN RESULT (dangling)`;
    };
    console.log(
      `\n  [0] REVOLVE — ${c.angleDeg}°${c.fullRevolution ? ' (FULL revolution)' : ''}, volume ${c.resultVolume}`,
    );
    console.log(`      caps:  FirstShape() = ${cap('first')}     LastShape() = ${cap('last')}`);
    console.log('      what each AUTHORED segment generated (the `lateral.k` rule):');
    for (const g of c.segGenerated) {
      const verdict =
        g.faces === 1
          ? '✓ exactly one face — nameable as lateral.' + g.seg
          : g.faces === 0
            ? `⚠ NO FACE (${g.edges} edge(s), ${g.degenerateEdges} degenerate) — ON THE AXIS`
            : `⚠ ${g.faces} FACES — the segment index is not an identity`;
      console.log(`        seg.${g.seg}  faces=${g.faces} edges=${g.edges}   ${verdict}`);
    }
  }

  // ---- 1. HISTORY: how is each output sub-shape reached? ----------------------------------------
  const byKind = Object.fromEntries(KINDS.map((k) => [k, []]));
  for (const o of c.outputs) byKind[o.out.split('#')[0]].push(o);

  console.log('\n  [1] HISTORY — how the maker accounts for each output sub-shape');
  console.log(
    `    ${pad('kind', 8)}${pad('total', 7)}${pad('identity', 10)}${pad('modified', 10)}${pad('generated', 11)}no history`,
  );
  for (const k of KINDS) {
    const os = byKind[k];
    const id = os.filter((o) => rel(o, 'identity').length).length;
    const mo = os.filter((o) => rel(o, 'modified').length).length;
    const ge = os.filter((o) => rel(o, 'generated').length).length;
    const none = os.filter((o) => o.from.length === 0).length;
    console.log(
      `    ${pad(k, 8)}${pad(os.length, 7)}${pad(id, 10)}${pad(mo, 10)}${pad(ge, 11)}${none ? `⚠ ${none}` : '0'}`,
    );
  }

  // ---- 2. ADJACENCY: close the gap ---------------------------------------------------------------
  // A face is nameable if history reaches it. An edge/vertex is nameable if history reaches it OR
  // its bounding faces are ALL nameable and identify it uniquely.
  const namedFaces = new Set(byKind.face.filter((o) => o.from.length > 0).map((o) => o.out));
  const faceKey = (o) => [...o.faces].sort().join(' & ');

  const closure = (kind, needDistinct) => {
    const out = { history: 0, adjacency: 0, endpoints: 0, refused: [] };
    const keys = new Map();
    for (const o of byKind[kind]) {
      const key = faceKey(o);
      keys.set(key, (keys.get(key) ?? 0) + 1);
    }
    // The finer key, used only where the face set alone is ambiguous: the faces PLUS the endpoints.
    const fineKey = (o) => `${faceKey(o)} @ ${[...(o.ends ?? [])].sort().join(',')}`;
    const fine = new Map();
    for (const o of byKind[kind]) fine.set(fineKey(o), (fine.get(fineKey(o)) ?? 0) + 1);

    for (const o of byKind[kind]) {
      if (o.from.length > 0) {
        out.history++;
        continue;
      }
      const allNamed = o.faces.length > 0 && o.faces.every((f) => namedFaces.has(f));
      const enough = o.faces.length >= needDistinct;
      if (!allNamed || !enough) {
        out.refused.push({
          o,
          why: !enough
            ? `only ${o.faces.length} distinct face(s)${o.seam ? ' — SEAM' : ''}`
            : 'a bounding face is itself unnamed',
        });
        continue;
      }
      if (keys.get(faceKey(o)) === 1) {
        out.adjacency++;
      } else if (kind === 'edge' && (o.ends?.length ?? 0) === 2 && fine.get(fineKey(o)) === 1) {
        // The face pair repeats, but the endpoints separate them — still fully structural.
        out.endpoints++;
      } else {
        out.refused.push({
          o,
          why: `AMBIGUOUS — ${keys.get(faceKey(o))} ${kind}s share the face set ${faceKey(o)}, and the endpoints do not separate them`,
        });
      }
    }
    return out;
  };

  const eClosure = closure('edge', 2); // an edge needs 2 distinct faces
  const vClosure = closure('vertex', 3); // a vertex needs 3 (in general position)

  console.log('\n  [2] + ADJACENCY — naming what history missed, from the faces that bound it');
  console.log(
    `    ${pad('kind', 8)}${pad('total', 7)}${pad('by history', 12)}${pad('by faces', 10)}${pad('+ endpoints', 13)}STILL UNNAMEABLE`,
  );
  for (const [k, cl] of [
    ['edge', eClosure],
    ['vertex', vClosure],
  ]) {
    const bad = cl.refused.length;
    console.log(
      `    ${pad(k, 8)}${pad(byKind[k].length, 7)}${pad(cl.history, 12)}${pad(cl.adjacency, 10)}${pad(cl.endpoints, 13)}${bad ? `⚠ ${bad}` : '✓ 0'}`,
    );
  }

  const unnamedFaces = byKind.face.filter((o) => o.from.length === 0);
  if (unnamedFaces.length) {
    console.log(
      `\n    ⚠ ${unnamedFaces.length} FACE(S) HAVE NO HISTORY AT ALL — everything below them is lost:`,
    );
    for (const o of unnamedFaces) {
      console.log(
        `        ${pad(o.out, 10)} ${o.geom.surface} area=${o.geom.area} at [${o.geom.centroid}]`,
      );
    }
  }

  for (const [k, cl] of [
    ['edge', eClosure],
    ['vertex', vClosure],
  ]) {
    if (!cl.refused.length) continue;
    console.log(
      `\n    ⚠ UNNAMEABLE ${k.toUpperCase()}S (${cl.refused.length}) — the resolver would have to REFUSE these:`,
    );
    for (const { o, why } of cl.refused.slice(0, 10)) {
      const g = o.geom ? `${o.geom.curve} len=${o.geom.length}` : '';
      console.log(`        ${pad(o.out, 10)} ${pad(g, 24)} ${why}`);
    }
    if (cl.refused.length > 10) console.log(`        … and ${cl.refused.length - 10} more`);
  }

  // ---- 3. The structural facts behind the numbers ------------------------------------------------
  const splits = (c.relations ?? []).filter(
    (r) => r.in.includes(':face:') && r.modified.length > 1,
  );
  if (splits.length) {
    console.log(
      '\n  [3] FACE SPLITS — one input face becoming several output faces (they SHARE a role,',
    );
    console.log('      so the role alone is not an identity: each needs an occurrence index):');
    for (const s of splits) {
      console.log(`      ${pad(s.in, 26)} → ${s.modified.length} faces: ${s.modified.join(', ')}`);
    }
  }

  const generators = (c.relations ?? []).filter((r) => r.generated.length > 0);
  if (generators.length) {
    console.log(
      '\n  [4] GENERATED — sub-shapes that exist in NEITHER input (the section curves, the fillet face):',
    );
    for (const g of generators) {
      console.log(`      ${pad(g.in, 26)} → ${g.generated.join(', ')}`);
    }
  }

  const deleted = (c.relations ?? []).filter((r) => r.deleted);
  if (deleted.length) {
    const kinds = { face: 0, edge: 0, vertex: 0 };
    for (const d of deleted) kinds[d.in.split(':')[1]]++;
    console.log(
      `\n  [5] DELETED — ${deleted.length} input sub-shape(s) reported gone ` +
        `(${kinds.face}F / ${kinds.edge}E / ${kinds.vertex}V)`,
    );
  }

  const dangling = (c.relations ?? []).reduce((n, r) => n + r.dangling, 0);
  if (dangling) {
    console.log(`\n  ⚠ DANGLING: history named ${dangling} shape(s) that are NOT in the result.`);
  }
}
console.log();
