// probe.cpp — A MEASUREMENT INSTRUMENT. It is NOT part of the shipped kernel.
//
// WHY THIS FILE EXISTS (spec §4.5, current_state.md §5 task 1). Persistent naming is the #1 risk in
// the project, and the spec is explicit that our knowledge of it is second-hand: OCCT's
// `Generated`/`Modified`/`IsDeleted` history is "robust for faces but historically weakest for edges
// and vertices generated by boolean section curves". That sentence is a citation, not a measurement.
// Before designing the naming resolver we find out what OCCT 7.9.3 ACTUALLY reports, on the shapes
// Bunyan actually needs: a cylinder, a boolean, a fillet, and the hardest case of all — a fillet on
// an edge that a boolean created.
//
// It links as its own WASM module so that the shipped kernel stays clean until the measurements say
// what to build. It prints; it does not name. Nothing here is on the identity path.
//
// ⚠ ONE DELIBERATE VIOLATION OF THE PROJECT'S OWN RULE, AND IT IS CONFINED TO THIS FILE.
// The naming rule (D1) is that identity NEVER comes from geometry. This probe labels sub-shapes
// geometrically (centroid, area, kind of surface) — because a measurement instrument's job is to
// describe what came out so a human can read it. That is the opposite of assigning identity from it.
// No output of this file is consumed by the kernel; it is consumed by a person.

#include <emscripten/bind.h>

#include <BRepPrimAPI_MakeBox.hxx>
#include <BRepPrimAPI_MakeCylinder.hxx>
#include <BRepPrim_Cylinder.hxx>
#include <BRepAlgoAPI_Cut.hxx>
#include <BRepAlgoAPI_Fuse.hxx>
#include <BRepAlgoAPI_Common.hxx>
#include <BRepFilletAPI_MakeFillet.hxx>
#include <BRepBuilderAPI_MakeShape.hxx>
#include <BRepGProp.hxx>
#include <GProp_GProps.hxx>
#include <BRep_Tool.hxx>
#include <BRepAdaptor_Curve.hxx>
#include <BRepAdaptor_Surface.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Edge.hxx>
#include <TopExp.hxx>
#include <TopExp_Explorer.hxx>
#include <TopTools_IndexedMapOfShape.hxx>
#include <TopTools_IndexedDataMapOfShapeListOfShape.hxx>
#include <TopTools_ListOfShape.hxx>
#include <Standard_Failure.hxx>
#include <gp_Ax2.hxx>
#include <gp_Pnt.hxx>
#include <gp_Dir.hxx>

#include <algorithm>
#include <map>
#include <sstream>
#include <string>
#include <vector>

namespace {

// ---------------------------------------------------------------------------------------------
// JSON, by hand. The probe's output is data, so the analysis lives in JS where it is easy to read.
// ---------------------------------------------------------------------------------------------
std::string quote(const std::string& s) { return "\"" + s + "\""; }

std::string num(double v) {
  std::ostringstream o;
  o.precision(6);
  o << std::fixed << v;
  return o.str();
}

const char* kindName(TopAbs_ShapeEnum k) {
  switch (k) {
    case TopAbs_FACE: return "face";
    case TopAbs_EDGE: return "edge";
    case TopAbs_VERTEX: return "vertex";
    default: return "other";
  }
}

// ---------------------------------------------------------------------------------------------
// A shape plus a HUMAN-READABLE label for each of its sub-shapes.
//
// For the OPERANDS the labels are the roles the operation itself supplies (MakeBox::BackFace(),
// BRepPrim_Cylinder::LateralFace(), …) — i.e. exactly what the real kernel is allowed to use. Edges
// and vertices are labelled structurally, by the faces that bound them, exactly as kernel.cpp does.
// So the operand side of the report is written in the vocabulary the resolver will actually have.
// ---------------------------------------------------------------------------------------------
struct Labelled {
  std::string name;
  TopoDS_Shape shape;
  TopTools_IndexedMapOfShape faces, edges, verts;
  std::map<int, std::string> faceLabel, edgeLabel, vertLabel;

  void index() {
    TopExp::MapShapes(shape, TopAbs_FACE, faces);
    TopExp::MapShapes(shape, TopAbs_EDGE, edges);
    TopExp::MapShapes(shape, TopAbs_VERTEX, verts);
  }

  // Edges and vertices are named by the faces that bound them — the structural rule kernel.cpp
  // already uses for a box. Applying it to the operands tells us, for free, where it starts failing.
  void labelFromAdjacency() {
    TopTools_IndexedDataMapOfShapeListOfShape edgeFaces, vertFaces;
    TopExp::MapShapesAndAncestors(shape, TopAbs_EDGE, TopAbs_FACE, edgeFaces);
    TopExp::MapShapesAndAncestors(shape, TopAbs_VERTEX, TopAbs_FACE, vertFaces);

    const auto boundedBy = [&](const TopoDS_Shape& sub,
                               const TopTools_IndexedDataMapOfShapeListOfShape& anc) {
      std::vector<std::string> labels;
      const int at = anc.FindIndex(sub);
      if (at == 0) return labels;
      for (TopTools_ListOfShape::Iterator it(anc.FindFromIndex(at)); it.More(); it.Next()) {
        const int fi = faces.FindIndex(it.Value());
        const auto found = faceLabel.find(fi);
        const std::string l = found == faceLabel.end() ? "?" : found->second;
        // DISTINCT faces only: a seam edge appears twice in the ancestor list of its own face, and
        // that duplicate is precisely the signal we are hunting for.
        if (std::find(labels.begin(), labels.end(), l) == labels.end()) labels.push_back(l);
      }
      std::sort(labels.begin(), labels.end());
      return labels;
    };

    const auto join = [](const std::vector<std::string>& v) {
      std::string s;
      for (std::size_t i = 0; i < v.size(); ++i) s += (i ? "|" : "") + v[i];
      return s.empty() ? std::string("<none>") : s;
    };

    for (int i = 1; i <= edges.Extent(); ++i) edgeLabel[i] = join(boundedBy(edges(i), edgeFaces));
    for (int i = 1; i <= verts.Extent(); ++i) vertLabel[i] = join(boundedBy(verts(i), vertFaces));
  }

  std::string keyOf(TopAbs_ShapeEnum k, int i) const {
    const std::map<int, std::string>* m =
        k == TopAbs_FACE ? &faceLabel : (k == TopAbs_EDGE ? &edgeLabel : &vertLabel);
    const auto found = m->find(i);
    return name + ":" + kindName(k) + ":" + (found == m->end() ? "?" : found->second);
  }
};

Labelled makeBoxAt(const std::string& name, double x, double y, double z, double dx, double dy,
                   double dz) {
  BRepPrimAPI_MakeBox mk(gp_Pnt(x, y, z), dx, dy, dz);
  Labelled L;
  L.name = name;
  L.shape = mk.Shape();
  L.index();
  // The measured translation table (Entry 7): OCCT's Back=x-min, Front=x-max, Left=y-min,
  // Right=y-max. Named from the operation's accessors, never from coordinates.
  const TopoDS_Face* const f[6] = {&mk.BackFace(),   &mk.FrontFace(), &mk.LeftFace(),
                                   &mk.RightFace(),  &mk.BottomFace(), &mk.TopFace()};
  const char* const roles[6] = {"x-min", "x-max", "y-min", "y-max", "z-min", "z-max"};
  for (int i = 0; i < 6; ++i) L.faceLabel[L.faces.FindIndex(*f[i])] = roles[i];
  L.labelFromAdjacency();
  return L;
}

Labelled makeCylinderAt(const std::string& name, const gp_Ax2& axis, double r, double h) {
  BRepPrimAPI_MakeCylinder mk(axis, r, h);
  Labelled L;
  L.name = name;
  L.shape = mk.Shape();
  L.index();
  // A cylinder's faces have semantic accessors too — so they are nameable from the operation, just
  // like a box's. THE QUESTION IS ITS EDGES: a full cylinder has a SEAM.
  BRepPrim_Cylinder& c = mk.Cylinder();
  L.faceLabel[L.faces.FindIndex(c.LateralFace())] = "lateral";
  L.faceLabel[L.faces.FindIndex(c.BottomFace())] = "cap.bottom";
  L.faceLabel[L.faces.FindIndex(c.TopFace())] = "cap.top";
  L.labelFromAdjacency();
  return L;
}

// ---------------------------------------------------------------------------------------------
// Descriptors. Geometry, for a HUMAN reading the report (see the header warning).
// ---------------------------------------------------------------------------------------------
std::string describeFace(const TopoDS_Face& f) {
  GProp_GProps p;
  BRepGProp::SurfaceProperties(f, p);
  const gp_Pnt c = p.CentreOfMass();
  BRepAdaptor_Surface s(f);
  const char* type = "other";
  switch (s.GetType()) {
    case GeomAbs_Plane: type = "plane"; break;
    case GeomAbs_Cylinder: type = "cylinder"; break;
    case GeomAbs_Torus: type = "torus"; break;
    case GeomAbs_Sphere: type = "sphere"; break;
    case GeomAbs_BSplineSurface: type = "bspline"; break;
    default: break;
  }
  std::ostringstream o;
  o << "{\"surface\":" << quote(type) << ",\"area\":" << num(p.Mass()) << ",\"centroid\":["
    << num(c.X()) << "," << num(c.Y()) << "," << num(c.Z()) << "]}";
  return o.str();
}

std::string describeEdge(const TopoDS_Edge& e) {
  std::ostringstream o;
  const bool degen = BRep_Tool::Degenerated(e);
  const char* type = "other";
  double length = 0.0;
  gp_Pnt c(0, 0, 0);
  if (!degen) {
    GProp_GProps p;
    BRepGProp::LinearProperties(e, p);
    length = p.Mass();
    c = p.CentreOfMass();
    BRepAdaptor_Curve a(e);
    switch (a.GetType()) {
      case GeomAbs_Line: type = "line"; break;
      case GeomAbs_Circle: type = "circle"; break;
      case GeomAbs_Ellipse: type = "ellipse"; break;
      case GeomAbs_BSplineCurve: type = "bspline"; break;
      case GeomAbs_BezierCurve: type = "bezier"; break;
      default: break;
    }
  }
  o << "{\"curve\":" << quote(degen ? "degenerate" : type) << ",\"length\":" << num(length)
    << ",\"midpoint\":[" << num(c.X()) << "," << num(c.Y()) << "," << num(c.Z()) << "]}";
  return o.str();
}

// ---------------------------------------------------------------------------------------------
// THE MEASUREMENT.
//
// For every sub-shape of every operand: IsDeleted / Modified / Generated, as the maker reports them.
// For every sub-shape of the RESULT: its ancestors, obtained by inverting the above. An output
// sub-shape with NO ancestor is an ORPHAN — the naming resolver cannot derive an identity for it from
// history, and that is precisely what we are counting.
//
// Independently, for every output EDGE: how many DISTINCT output faces bound it. That is the other
// derivation available to us (kernel.cpp's face-pair rule), and reporting both lets us check one
// against the other instead of trusting either.
// ---------------------------------------------------------------------------------------------
std::string probeCase(const std::string& caseName, const std::string& note,
                      std::vector<Labelled>& operands, BRepBuilderAPI_MakeShape& maker,
                      const TopoDS_Shape& result) {
  TopTools_IndexedMapOfShape outF, outE, outV;
  TopExp::MapShapes(result, TopAbs_FACE, outF);
  TopExp::MapShapes(result, TopAbs_EDGE, outE);
  TopExp::MapShapes(result, TopAbs_VERTEX, outV);

  const auto outIndex = [&](const TopoDS_Shape& s) -> std::pair<TopAbs_ShapeEnum, int> {
    if (s.ShapeType() == TopAbs_FACE) return {TopAbs_FACE, outF.FindIndex(s)};
    if (s.ShapeType() == TopAbs_EDGE) return {TopAbs_EDGE, outE.FindIndex(s)};
    if (s.ShapeType() == TopAbs_VERTEX) return {TopAbs_VERTEX, outV.FindIndex(s)};
    return {s.ShapeType(), 0};
  };

  // outKey -> list of "<operand key> (relation)"
  std::map<std::string, std::vector<std::string>> ancestors;
  const auto outKey = [](TopAbs_ShapeEnum k, int i) {
    return std::string(kindName(k)) + "#" + std::to_string(i);
  };

  // ⚠ THE RELATION THAT IS EASY TO FORGET, AND WHOSE ABSENCE MAKES HISTORY LOOK FAR WORSE THAN IT IS.
  //
  // `Modified()` returns only the SPLITS of a shape. An input sub-shape the operation never touched
  // is not "modified" — it is passed through into the result as the SAME TopoDS_Shape, and history
  // says nothing about it at all. Read naively, that silence looks identical to "OCCT cannot tell me
  // where this came from", and a resolver built on that misreading would refuse to name faces it
  // already knows perfectly well.
  //
  // So the identity relation is measured FIRST, and separately: is this output sub-shape literally
  // the same shape as one of the inputs? (`IsSame` = same TShape + location, ignoring orientation —
  // which is exactly the equivalence OCCT's own shape maps use.)
  for (Labelled& L : operands) {
    const TopAbs_ShapeEnum kinds[3] = {TopAbs_FACE, TopAbs_EDGE, TopAbs_VERTEX};
    for (const TopAbs_ShapeEnum k : kinds) {
      const TopTools_IndexedMapOfShape& m =
          k == TopAbs_FACE ? L.faces : (k == TopAbs_EDGE ? L.edges : L.verts);
      const TopTools_IndexedMapOfShape& out =
          k == TopAbs_FACE ? outF : (k == TopAbs_EDGE ? outE : outV);
      for (int i = 1; i <= m.Extent(); ++i) {
        const int at = out.FindIndex(m(i));
        if (at != 0) ancestors[outKey(k, at)].push_back(L.keyOf(k, i) + " (identity)");
      }
    }
  }

  std::ostringstream rel;  // the operand -> result side of the report
  rel << "[";
  bool firstRel = true;

  for (Labelled& L : operands) {
    const TopAbs_ShapeEnum kinds[3] = {TopAbs_FACE, TopAbs_EDGE, TopAbs_VERTEX};
    for (const TopAbs_ShapeEnum k : kinds) {
      const TopTools_IndexedMapOfShape& m =
          k == TopAbs_FACE ? L.faces : (k == TopAbs_EDGE ? L.edges : L.verts);
      for (int i = 1; i <= m.Extent(); ++i) {
        const TopoDS_Shape& sub = m(i);
        const std::string key = L.keyOf(k, i);

        const bool deleted = maker.IsDeleted(sub) == Standard_True;

        // ⚠ Modified()/Generated() can name a shape that is NOT in the result. We count those
        // separately as "dangling" rather than quietly dropping them — a resolver that trusted the
        // history blindly would bind an identity to a shape nobody can see.
        std::ostringstream mods, gens;
        int nMod = 0, nGen = 0, dangling = 0;
        mods << "[";
        gens << "[";

        const auto walk = [&](const TopTools_ListOfShape& list, std::ostringstream& out, int& count,
                              const char* relation) {
          for (TopTools_ListOfShape::Iterator it(list); it.More(); it.Next()) {
            const auto [k2, i2] = outIndex(it.Value());
            if (i2 == 0) {
              ++dangling;
              continue;
            }
            if (count++) out << ",";
            out << quote(outKey(k2, i2));
            ancestors[outKey(k2, i2)].push_back(key + " (" + relation + ")");
          }
        };

        try {
          walk(maker.Modified(sub), mods, nMod, "modified");
        } catch (const Standard_Failure&) {
          // Some makers throw on an unsupported sub-shape type rather than returning an empty list.
          // That itself is a finding: it means the resolver may not ask the question naively.
          mods << quote("<threw>");
        }
        try {
          walk(maker.Generated(sub), gens, nGen, "generated");
        } catch (const Standard_Failure&) {
          gens << quote("<threw>");
        }
        mods << "]";
        gens << "]";

        if (!firstRel) rel << ",";
        firstRel = false;
        rel << "{\"in\":" << quote(key) << ",\"deleted\":" << (deleted ? "true" : "false")
            << ",\"modified\":" << mods.str() << ",\"generated\":" << gens.str()
            << ",\"dangling\":" << dangling << "}";
      }
    }
  }
  rel << "]";

  // The result side: every output sub-shape, its ancestry, and — for edges — how many distinct
  // output faces bound it (the face-pair rule's own view of the same edge).
  TopTools_IndexedDataMapOfShapeListOfShape outEdgeFaces, outVertFaces;
  TopExp::MapShapesAndAncestors(result, TopAbs_EDGE, TopAbs_FACE, outEdgeFaces);
  TopExp::MapShapesAndAncestors(result, TopAbs_VERTEX, TopAbs_FACE, outVertFaces);

  // The distinct output faces bounding a sub-shape. This is the OTHER derivation available to us:
  // if every face can be named, an edge can be named by the pair of faces it lies between and a
  // vertex by the set of faces that meet at it — with no history at all. Reporting it alongside the
  // history lets each check the other, instead of trusting either on its own.
  const auto boundingFaces = [&](const TopoDS_Shape& sub,
                                 const TopTools_IndexedDataMapOfShapeListOfShape& anc,
                                 bool* repeated) {
    std::vector<int> distinct;
    const int at = anc.FindIndex(sub);
    if (at == 0) return distinct;
    for (TopTools_ListOfShape::Iterator it(anc.FindFromIndex(at)); it.More(); it.Next()) {
      const int fi = outF.FindIndex(it.Value());
      if (std::find(distinct.begin(), distinct.end(), fi) == distinct.end()) distinct.push_back(fi);
      else if (repeated != nullptr) *repeated = true;
    }
    std::sort(distinct.begin(), distinct.end());
    return distinct;
  };

  std::ostringstream outs;
  outs << "[";
  bool firstOut = true;
  const TopAbs_ShapeEnum kinds[3] = {TopAbs_FACE, TopAbs_EDGE, TopAbs_VERTEX};
  for (const TopAbs_ShapeEnum k : kinds) {
    const TopTools_IndexedMapOfShape& m =
        k == TopAbs_FACE ? outF : (k == TopAbs_EDGE ? outE : outV);
    for (int i = 1; i <= m.Extent(); ++i) {
      const std::string key = outKey(k, i);
      if (!firstOut) outs << ",";
      firstOut = false;

      outs << "{\"out\":" << quote(key) << ",\"from\":[";
      const auto found = ancestors.find(key);
      if (found != ancestors.end()) {
        for (std::size_t a = 0; a < found->second.size(); ++a) {
          outs << (a ? "," : "") << quote(found->second[a]);
        }
      }
      outs << "]";

      const auto emitFaces = [&](const std::vector<int>& fs) {
        outs << ",\"faces\":[";
        for (std::size_t a = 0; a < fs.size(); ++a) {
          outs << (a ? "," : "") << quote(outKey(TopAbs_FACE, fs[a]));
        }
        outs << "]";
      };

      if (k == TopAbs_FACE) {
        outs << ",\"geom\":" << describeFace(TopoDS::Face(m(i)));
      } else if (k == TopAbs_EDGE) {
        const TopoDS_Edge& e = TopoDS::Edge(m(i));
        outs << ",\"geom\":" << describeEdge(e);

        // How many DISTINCT output faces bound this edge? 2 = the face-pair rule can name it.
        // 1 = a seam (the same face on both sides) — the rule refuses, and today's kernel FAILS.
        bool seam = false;
        emitFaces(boundingFaces(e, outEdgeFaces, &seam));

        // The edge's ENDPOINTS. If two edges lie between the same pair of faces, the face pair is
        // not an identity — but the vertices they run between may still tell them apart, and a
        // vertex is itself nameable by the faces that meet at it. This is the last structural
        // discriminator available before the resolver would have to reach for geometry.
        TopoDS_Vertex v1, v2;
        TopExp::Vertices(e, v1, v2);
        outs << ",\"ends\":[";
        bool firstEnd = true;
        for (const TopoDS_Vertex& v : {v1, v2}) {
          if (v.IsNull()) continue;
          const int vi = outV.FindIndex(v);
          if (vi == 0) continue;
          outs << (firstEnd ? "" : ",") << quote(outKey(TopAbs_VERTEX, vi));
          firstEnd = false;
        }
        outs << "]";

        outs << ",\"seam\":" << (seam ? "true" : "false")
             << ",\"degenerate\":" << (BRep_Tool::Degenerated(e) ? "true" : "false");
      } else {
        // A vertex is where faces meet — so the same idea, one dimension down: the SET of faces
        // meeting at it. Whether that set is unique per vertex is a question, not an assumption.
        emitFaces(boundingFaces(m(i), outVertFaces, nullptr));
      }
      outs << "}";
    }
  }
  outs << "]";

  std::ostringstream o;
  o << "{\"case\":" << quote(caseName) << ",\"note\":" << quote(note) << ",\"operands\":[";
  for (std::size_t i = 0; i < operands.size(); ++i) {
    o << (i ? "," : "") << "{\"name\":" << quote(operands[i].name)
      << ",\"faces\":" << operands[i].faces.Extent() << ",\"edges\":" << operands[i].edges.Extent()
      << ",\"vertices\":" << operands[i].verts.Extent() << "}";
  }
  o << "],\"result\":{\"faces\":" << outF.Extent() << ",\"edges\":" << outE.Extent()
    << ",\"vertices\":" << outV.Extent() << "},\"relations\":" << rel.str()
    << ",\"outputs\":" << outs.str() << "}";
  return o.str();
}

// A no-op maker, so a PRIMITIVE (no operands) can be reported through exactly the same code path.
class NullMaker : public BRepBuilderAPI_MakeShape {
 public:
  void Build(const Message_ProgressRange& = Message_ProgressRange()) override {}
};

std::string probePrimitive(const std::string& caseName, const std::string& note, Labelled& L) {
  std::vector<Labelled> none;
  NullMaker maker;
  return probeCase(caseName, note, none, maker, L.shape);
}

// The wall Bunyan actually builds: 3000 x 200 x 2500 mm.
Labelled wall() { return makeBoxAt("wall", 0, 0, 0, 3000, 200, 2500); }

std::string boolCase(const std::string& caseName, const std::string& note, Labelled a, Labelled b,
                     int kind /* 0=cut 1=fuse 2=common */) {
  TopTools_ListOfShape args, tools;
  args.Append(a.shape);
  tools.Append(b.shape);

  BRepAlgoAPI_Cut cut;
  BRepAlgoAPI_Fuse fuse;
  BRepAlgoAPI_Common common;
  BRepAlgoAPI_BooleanOperation* op = kind == 0   ? static_cast<BRepAlgoAPI_BooleanOperation*>(&cut)
                                     : kind == 1 ? static_cast<BRepAlgoAPI_BooleanOperation*>(&fuse)
                                                 : static_cast<BRepAlgoAPI_BooleanOperation*>(&common);
  op->SetArguments(args);
  op->SetTools(tools);
  op->Build();
  if (!op->IsDone()) return "{\"case\":" + quote(caseName) + ",\"error\":\"boolean not done\"}";

  std::vector<Labelled> operands{a, b};
  return probeCase(caseName, note, operands, *op, op->Shape());
}

}  // namespace

// ---------------------------------------------------------------------------------------------
// The six cases, cheapest first. The last one is the one the spec calls the resolver's hardest:
// a fillet chained onto an edge that a boolean created.
// ---------------------------------------------------------------------------------------------
std::string probe() {
  std::ostringstream o;
  o << "[";
  bool first = true;
  const auto add = [&](const std::string& s) {
    if (!first) o << ",";
    first = false;
    o << s;
  };

  try {
    // 1. A CYLINDER ON ITS OWN. Before any boolean: does today's face-pair edge rule even survive a
    //    curved primitive? A full cylinder closes on itself, so it has a SEAM edge.
    {
      Labelled c = makeCylinderAt("col", gp_Ax2(gp_Pnt(0, 0, 0), gp_Dir(0, 0, 1)), 150, 3000);
      add(probePrimitive("cylinder", "a 300mm-diameter, 3m column — the simplest curved primitive", c));
    }

    // 2. CUT: a rectangular opening through a wall. THE canonical BIM case (a window).
    add(boolCase("cut_box_box", "a 1000x1400 window cut clean through a 3000x200x2500 wall", wall(),
                 makeBoxAt("opening", 800, -50, 900, 1000, 300, 1400), 0));

    // 3. CUT: a circular opening (a duct penetration). Section curves are now CIRCLES, not lines.
    add(boolCase("cut_box_cylinder", "a 300mm circular penetration through the same wall", wall(),
                 makeCylinderAt("duct", gp_Ax2(gp_Pnt(1500, -50, 1250), gp_Dir(0, 1, 0)), 150, 300),
                 0));

    // 4. FUSE: two walls meeting in an L. Coplanar-face merging is where history gets interesting.
    add(boolCase("fuse_box_box", "two walls meeting at a corner", wall(),
                 makeBoxAt("wall-b", 2800, 0, 0, 200, 3000, 2500), 1));

    // 5. FILLET on a PRIMITIVE's edge. The easy fillet: the edge already has a structural name.
    {
      Labelled w = wall();
      // The vertical edge where x-max meets y-min.
      TopoDS_Edge target;
      for (int i = 1; i <= w.edges.Extent(); ++i) {
        if (w.edgeLabel[i] == "x-max|y-min") target = TopoDS::Edge(w.edges(i));
      }
      BRepFilletAPI_MakeFillet mk(w.shape);
      mk.Add(50.0, target);
      mk.Build();
      if (mk.IsDone()) {
        std::vector<Labelled> operands{w};
        add(probeCase("fillet_primitive_edge", "a 50mm fillet on the wall's x-max|y-min edge",
                      operands, mk, mk.Shape()));
      } else {
        add("{\"case\":\"fillet_primitive_edge\",\"error\":\"fillet not done\"}");
      }
    }

    // 6. ⚠ THE HARDEST CASE IN THE SPEC: a fillet on an edge PRODUCED BY A BOOLEAN.
    //    The chain is what matters: the boolean must give the edge a derivable identity, and the
    //    fillet must then accept that edge as its input and hand back a face we can name from it.
    //    The probe picks the target edge THE WAY THE RESOLVER WOULD HAVE TO — from the history, as
    //    an edge the boolean GENERATED (a section curve) — not by looking for it in space.
    {
      Labelled w = wall();
      Labelled opening = makeBoxAt("opening", 800, -50, 900, 1000, 300, 1400);

      TopTools_ListOfShape args, tools;
      args.Append(w.shape);
      tools.Append(opening.shape);
      BRepAlgoAPI_Cut cut;
      cut.SetArguments(args);
      cut.SetTools(tools);
      cut.Build();

      if (!cut.IsDone()) {
        add("{\"case\":\"fillet_boolean_edge\",\"error\":\"cut not done\"}");
      } else {
        const TopoDS_Shape cutShape = cut.Shape();

        // Every edge the cut GENERATED from a face of either operand — i.e. a section curve, an edge
        // that exists in neither input. These are the edges the spec says are the weak spot.
        TopTools_IndexedMapOfShape cutEdges;
        TopExp::MapShapes(cutShape, TopAbs_EDGE, cutEdges);
        TopTools_IndexedMapOfShape generatedEdges;
        for (Labelled* L : {&w, &opening}) {
          for (int i = 1; i <= L->faces.Extent(); ++i) {
            for (TopTools_ListOfShape::Iterator it(cut.Generated(L->faces(i))); it.More();
                 it.Next()) {
              if (it.Value().ShapeType() == TopAbs_EDGE && cutEdges.Contains(it.Value())) {
                generatedEdges.Add(it.Value());
              }
            }
          }
        }

        std::ostringstream pick;
        pick << "{\"case\":\"fillet_boolean_edge_target\",\"note\":\"which edges the CUT generated\","
             << "\"generatedEdgeCount\":" << generatedEdges.Extent()
             << ",\"cutEdgeCount\":" << cutEdges.Extent() << ",\"targets\":[";
        for (int i = 1; i <= generatedEdges.Extent(); ++i) {
          pick << (i > 1 ? "," : "") << describeEdge(TopoDS::Edge(generatedEdges(i)));
        }
        pick << "]}";
        add(pick.str());

        if (generatedEdges.Extent() == 0) {
          add("{\"case\":\"fillet_boolean_edge\",\"error\":\"the cut generated NO edges — the "
              "section curves have no ancestry at all\"}");
        } else {
          // Fillet ONE of them: a vertical edge of the opening's reveal.
          BRepFilletAPI_MakeFillet mk(cutShape);
          mk.Add(30.0, TopoDS::Edge(generatedEdges(1)));
          mk.Build();
          if (!mk.IsDone()) {
            add("{\"case\":\"fillet_boolean_edge\",\"error\":\"fillet on a boolean edge NOT DONE\"}");
          } else {
            // The operand of the fillet is the CUT RESULT, whose sub-shapes have no names of their
            // own yet — so label them by their own adjacency, which is what the resolver will have
            // after it has named the boolean's output.
            Labelled c;
            c.name = "cut";
            c.shape = cutShape;
            c.index();
            for (int i = 1; i <= c.faces.Extent(); ++i) {
              c.faceLabel[i] = "f" + std::to_string(i);
            }
            c.labelFromAdjacency();
            std::vector<Labelled> operands{c};
            add(probeCase("fillet_boolean_edge",
                          "a 30mm fillet on an edge the CUT created — the spec's hardest case",
                          operands, mk, mk.Shape()));
          }
        }
      }
    }
  } catch (const Standard_Failure& e) {
    add(std::string("{\"case\":\"<fatal>\",\"error\":") + quote(e.GetMessageString()) + "}");
  } catch (...) {
    add("{\"case\":\"<fatal>\",\"error\":\"non-standard throw\"}");
  }

  o << "]";
  return o.str();
}

EMSCRIPTEN_BINDINGS(bunyan_probe) { emscripten::function("probe", &probe); }
